# Generated by Django 3.0.3 on 2020-04-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mcq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_no', models.CharField(help_text='Test Number', max_length=10)),
                ('q_no', models.IntegerField(help_text='Question number')),
                ('ques', models.TextField(help_text='Question Description')),
                ('op1', models.CharField(help_text='Option 1', max_length=100)),
                ('op2', models.CharField(help_text='Option 2', max_length=100)),
                ('op3', models.CharField(help_text='Option 3', max_length=100)),
                ('op4', models.CharField(help_text='Option 4', max_length=100)),
                ('ans1', models.BooleanField(help_text='Answer option number1')),
                ('ans2', models.BooleanField(help_text='Answer option number2')),
                ('ans3', models.BooleanField(help_text='Answer option number3')),
                ('ans4', models.BooleanField(help_text='Answer option number4')),
                ('points', models.IntegerField(help_text='Marks alooted to this question')),
            ],
            options={
                'ordering': ['q_no'],
            },
        ),
    ]
