# Generated by Django 3.0.3 on 2020-07-22 10:22

from django.db import migrations, models
import exam.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='used',
            field=models.BooleanField(default=False, help_text='answered or not'),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='test_no',
            field=models.CharField(default=exam.models.Mcq.random_string, help_text='Test Number', max_length=10),
        ),
    ]
