# Generated by Django 3.0.3 on 2020-07-22 13:15

from django.db import migrations, models
import exam.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200722_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='test_no',
            field=models.CharField(default=exam.models.Mcq.random_string, help_text='Test Number please use this and same test number only for all questions replace if different and rember test id', max_length=10),
        ),
    ]
