# Generated by Django 3.0.3 on 2020-07-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200722_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq',
            name='used',
        ),
    ]
