# Generated by Django 3.0.3 on 2020-04-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_uid', models.CharField(help_text='Enter Your Test ID', max_length=10)),
                ('student', models.ManyToManyField(to='register.Student')),
            ],
            options={
                'ordering': ['test_uid'],
            },
        ),
    ]
