# Generated by Django 3.0.3 on 2020-04-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile_test_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='student',
        ),
        migrations.AddField(
            model_name='profile',
            name='student_emailid',
            field=models.EmailField(default='abc@abc.com', help_text='Confirm your email', max_length=254),
        ),
    ]
