# Generated by Django 3.0.3 on 2020-07-22 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200722_1845'),
        ('dashboard', '0003_auto_20200405_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test_id',
            field=models.ForeignKey(db_column='test_no', default=0, on_delete=django.db.models.deletion.CASCADE, to='exam.Mcq'),
        ),
    ]
