# Generated by Django 3.0.3 on 2020-07-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200722_1916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Joiners',
        ),
        migrations.AddField(
            model_name='profile',
            name='ques_id',
            field=models.IntegerField(default=0, help_text='Your ques id'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ques_used',
            field=models.IntegerField(default=0, help_text='Your ques id'),
        ),
    ]
