# Generated by Django 3.0.3 on 2020-07-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200722_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ques_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ques_used',
        ),
    ]
