# Generated by Django 3.0.3 on 2020-04-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_name', models.CharField(help_text='Enter Your Name', max_length=100)),
                ('student_email', models.EmailField(help_text='Enter Your Email ID', max_length=254, primary_key=True, serialize=False)),
                ('student_mobile', models.CharField(help_text='Enter Your Mobile Number', max_length=10)),
                ('student_password', models.CharField(help_text='Enter a strong password', max_length=30)),
            ],
            options={
                'ordering': ['student_name'],
            },
        ),
    ]
